### ISSUE TITLE
standby.rhardih.io appears to be down

### ISSUE THREAD

**Issue by ArtificialRaccoon** [rhardih/stand#1]
Navigating to the link mentioned in the README.md just results in a page saying "There's nothing here, yet. "

**Comment by rhardih** [comment]
Yes, this was previously hosted on a Heroku free tier and should be moved to some other free Ruby hosting provider.

**Comment by rhardih** [comment]
I've begun the process of moving https://github.com/rhardih/by to render.com instead, because they have a similar free tier as Heroku. This also entailed moving https://github.com/rhardih/stand off of Travis, which has been broken for a long time. Images can now be built using Github Actions instead and will be pushed to docker hub.

Only problem I have right now, is that render.com isn't immediately compatible with the way I run **by**, so I'm missing a connection to a _redis_ instance, which you will see on https://standby.rhardih.io right now.

I might just move to in-memory caching instead, but will work a bit more on it soon.

**Comment by rhardih** [comment]
Ok, turns out attaching a _redis_ instance wasn't entirely a problem after all. https://standby.rhardih.io is up and running again and triggering image builds should work as before.

I'll still have to do some testing, but I think this is good enough for now. 👍
