### ISSUE TITLE
STAND unable to locate python2, resulting builds fail (see "Actions" tab)

### ISSUE THREAD

**Issue by ArtificialRaccoon** [rhardih/stand#3]
I recently needed BAD to build copies of the GDAL for x86_64 using r18b Android-23, and noticed that STAND didn't have an image for that particular combination.  Using STANDBY, I launched a build, but notice it failed with "buildx failed with: ERROR: failed to solve: process "/bin/sh -c ./ndk.sh" did not complete successfully: exit code: 100".  I cloned the repo and determined that python2 was unable to be found by the ndk standalone build scripts.

Builds require access to Python2, however in the more recent Ubuntu images, calling "python" will no longer get you the default python interpreter.  Instead, we explicitly call whichever version we want (or we install the python-is-python3 metapackage if we are okay with defaulting to python3).

Since we want to explicitly use python2 ('make-standalone-toolchain' script require python2), we need to force the container to see python2 as python.  There is no metapackage 'python-is-python2', so that is not an option. I've tried using an alias with the shell option 'expand_aliases', however this also did not work.  The solution is to create a simple shell script inside the docker file to redirect to python2.

In the dockerfile, simply add the following after `COPY ndk.sh .` :

```
RUN echo '#!/usr/bin/python2' > /usr/bin/python && chmod +x /usr/bin/python
```

@rhardih I tested this change locally, and the toolchain build completed successfully.  Would you mind testing it and adding it to the repo?  I would like to pull that particular stand image for use with BAD in the near future :)  I can create a pull request if you feel it's necessary, though it is literally just that single line.

**Comment by rhardih** [comment]
Hi Bernard, thanks for pointing this out. The base image just being `ubuntu:latest` obviously is the culprit here, but it's probably better to follow along and fix these kinds of breakages, rather than staying on 16.04 which is ~7 years old now.

I pushed your fix, albeit slightly different, as the culprit as I saw it, was the fall-through in the `ndk.sh` to `apt install python`, which obviously failed. I've opted for a soft-link as well instead of a new script file.  Fix is in https://github.com/rhardih/stand/commit/ff5f817825614b16a15e3f979a13b158eb95d103
